
import "../globals.css";
import Sidebar from "@/components/sidebar/Sidebar";


import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

import MobileSidebarOverlay from "@/components/sidebar/MobileSidebarOverlay";
import Provider from "@/providers/MainProvider";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";
export const metadata = {
    title: "LMS Admin",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    return (
        <div className=" bg-cover bg-center ">
            <Provider session={session}>
                <div id="wrapper">
                    <MobileSidebarOverlay />
                    <Header/>
                    <Sidebar />
                    {children}
                    <Footer/>
                </div>
            </Provider>
        </div>
    );
}
